### ISSUE TITLE
Reworked/improved palettes for j2bs

### ISSUE THREAD

**Issue by 1280px** [1280px/hueblocks-new#1]
**jar2blockset:**
- Introduce new type of palletes!
  - "expr" palettes are calculated using expressions instead of includes/excludes lists, allowing to calculate them using actual RGB colorspace values.
  - Maybe use sth like this https://github.com/danthedeckie/simpleeval for eval instead of creating and locking down my own?
  - expr and includes/excludes can NOT be used together!
  - Example:
```
palettes:
  - name: 'Filter-based Pallete'
    includes: 
    - *wool.png
    - *concrete.png
    excludes:
    - red*

  - name: 'Expr-based Pallete'
    expr: "R > 100 && ((G - 30) < 100) || ((B + 30) > 200)"
```
  - Classic filter-based palettes will also be supported, and will have "filter" type

**vueblocks:**
- Allow creating custom palettes by selecting needed textures in blockpick
- Allow importing and exporting custom palettes using JSON
- ![Image](https://github.com/user-attachments/assets/d4190637-4d79-4d33-ac98-8b75d3e2a1ef)
